apiVersion: v1
kind: Pod
metadata:
  labels:
    app: build-ci
spec:
  containers:
    - name: docker-cmds
      image: docker:stable-git
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run
          name: docker-sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run
